const {saveFixtures} = require('../../helpers/init-fixtures')

describe('Home page tests', () => {
  before(async () => {
    return await cy.task('initDB')
  })
  beforeEach(async () => {
    return cy.visit('/')
  })
  it('Home page should render correctly', () => {
    cy.contains('Начать').click()
  })

  it("Calc input 'from' should work", () => {
    cy.get('.left__input input')
      .type('1')
      .should('have.value', '1')
  })

  it("Calc input 'to' should work", () => {
    cy.get('.right__input input')
      .type('1')
      .should('have.value', '1')
  })
  describe('Create payment', () => {
    it.only('Sould create payment correctly', () => {
      cy.get('.left__input input')
        .type('1.5')
        .get('[placeholder="ФИО"]')
        .type('Fake Fio')
        .get('main [placeholder="Почта"]')
        .type('fake@email.com')
        .get('[placeholder="Ваш bitcoin кошелек"]')
        .type('1J8rcVPwRjJdi1jhk95AsjMfsLBbP7x7pS')
        .get('[placeholder="Ваш номер для сбербанк руб"]')
        .type('1234 4321 5678 8765')
        .get('label[for="agree"]')
        .click()
        .get('button')
        .contains('Создать')
        .click()
        .url()
        .should('include', '/podtverjdenie-oplati')
        .get('button')
        .contains('Я перевел')
        .click()
        .url()
        .should('include', '/spasibo')
        .get('button')
        .contains('Следить за переводом')
        .click()
        .url()
        .should('include', '/perevod/')
    })
  })
  describe('Routing should work', () => {
    it('Home', () => {
      cy.contains('Резервы')
        .click()
        .url()
        .should('include', '/reservi')
      cy
        .scrollTo(0, -100)
        .get('a')
        .contains('Главная')
        .click()
        .url()
        .should('include', '/')
    })

    it('Reserves', () => {
      cy.contains('Резервы')
        .click()
        .url()
        .should('include', '/reservi')
        .get('button')
        .contains('Начать')
        .click()
        .url()
        .should('include', '/')
    })

    it('About', () => {
      cy.contains('О нас')
        .click()
        .url()
        .should('include', '/o-nas')
        .get('button')
        .contains('Начать')
        .click()
        .url()
        .should('include', '/')
    })

    it('FAQ', () => {
      cy.contains('FAQ')
        .click()
        .url()
        .should('include', '/faq')
        .get('button')
        .contains('Начать')
        .click()
        .url()
        .should('include', '/')
    })

    it('Auth', () => {
      cy.get('nav > span.auth-menu-item')
        .click()
        .contains('Войти')
        .click()
        .url()
        .should('include', '/lichnii-kabinet')
        .get('button')
        .contains('Начать')
        .click()
        .url()
        .should('include', '/')
    })

    it('Registration', () => {
      cy.get('nav > span.auth-menu-item')
        .click()
        .contains('Регистрация')
        .click()
        .url()
        .should('include', '/registracya')
        .get('button')
        .contains('Начать')
        .click()
        .url()
        .should('include', '/')
    })
  })
})
